test_that("blastn_output works - example 12S", {
  # should match KY815349.1 and KY815345.1
  aggregate_fasta <-
    c(
      ">KY815345.1
      GCCATCAGCTTTAACTAAACTTACACATGCGAGTATCCGCACCCCTGTGAGAATGCCCCGCTACCTCCTGATTGGAGACG
      AGGAGCTGGCATCAGGCACAATCTTCTTTAGCCCACGACGCCTTGCTAAGCCACACCCCCAAGGGAATTCAGCAGTGATA
      AATATTAAGCCATGAGTGAAAACTTGACTTAGTTAGTGTTTACAGGGCCGGTAAACCTCGTGCCAGCCACCGCGGTTAGA
      CGAGAGACCCAAGTGGATGGCCCTCGGCGTAAAGAGTGGTTAAGATAGTCCCAAACTAAGGCCAAACGACTTTTTAGCTG
      TTATACGCGCGAGAAGACATGAAGCCCAACTACGAAAGTGGCCTTAAGCCCCTGACCCCACGAAAGCTAGGATACAAACT
      GGGATTAGATACCCCACTATGCCTAGCCCTAAACATTGATAACACCCTACCCAGTTTATCCGCCCGGGAACTACGAGCGT
      CAGCTTGAAACCCAAAGGACTTGGCGGTGCTTTAGATCCACCTAGAGGAGCCTGTTCTAGAACCGATAATCCCCGTTCAA
      CCTCACCTTTTCTTGCTTATTCCGCCTATATACCACCGTCGTCAGCTTACTCTTTGAGGAACTAGCCGTAAGCGCAACTG
      GTACAACCTAAAACGCCAGGTCGAGGTGTAGCGAATGGAAAGGGAAGAAATGGGCTACATTCAGTAATAATAATGCATAC
      GAACGATGTTCTGAAATAAACATCTGAAGGAGGATTTAGTAGTAAGTAGAGAGCAGAGTGCTCTACTGAAGCCGGCCCTG
      AAGCGCGTACACACCGCCCGTCACTCTCCCCGAGCTAACCAAACACATTACTAATAAACAAAACTTGCAAAGGGGAGGC"
    )
  
  blast_db_path <-
    file.path(system.file(package = 'rCRUX', 'mock-db/blastdb'), 'mock-db')
  
  blastn_output <-
    run_blastn(
      fasta = aggregate_fasta,
      db = blast_db_path,
      evalue = 1e-6,
      align = 50000,
      coverage = 50,
      perID = 90,
      num_threads = 1
    )
  
  expect_true(all(blastn_output$accession %in% c('KY815349.1', 'KY815345.1')))
  
  
})

test_that("blastn_output works - example 16S", {
  aggregate_fasta <-
    c(
      ">FP929003.1:674-1491 Candidatus Nitrospira defluvii; FP929003
   CCCGGTGTAGCGGTGAAATGCGTAGAGATCGGGAGGAAGGCCGGTGGCGAAGGCGGCGCTCTGGAACATACCTGACGCTG
   AGACACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCCTAAACTATGGATACTAAGTGTCGGCG
   GGTTACCGCCGGTGCCGCAGCTAACGCATTAAGTATCCCGCCTGGGAAGTACGGCCGCAAGGTTGAAACTCAAAGGAATT
   GACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGACGCAACGCGAAGAACCTTACCCAGGTTGGACATGCAC
   GTAGTAGAAAGGTGAAAGCCTGACGAGGTAGCAATACCAGCGTGNCTCAGGTGCTGCATGGCTGTCGTCAGCTCGTGCCG
   TGAGGTGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCTTTCAGTTGCTACCGGGTCATGCCGAGCACTCTGAAAGG
   ACTGCCCAGGATAACGGGGAGGAAGGTGGGGATGACGTCAAGTCAGCATGGCCTTTATGCCTGGGGCCACACACGTGCTA
   CAATGGCCGGTACAAAGCGCTGCAAACCTGCAAAGGGGAGCCAATCGCAAAAAACCGGCCTCAGTTCAGATTGAGGTCTG
   CAACTCGACCTCATGAAGGCGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTTCCCGGGCCTTGTACA
   CACCGCCCGTCACACCACGAAAGCCTGTTGTACCTGAAGTCGCCCAAGCCAACCGCAAGGAGGCAGGCGCCCACGGTATG
   GCCGGTGATTGGGGTGAA",
      ">EU559167.1:674-1491 Candidatus Nitrospira defluvii; Contig5882; EU559167
   CCCGGTGTAGCGGTGAAATGCGTAGAGATCGGGAGGAAGGCCGGTGGCGAAGGCGGCGCTCTGGAACATACCTGACGCTG
   AGACACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCCTAAACTATGGATACTAAGTGTCGGCG
   GGTTACCGCCGGTGCCGCAGCTAACGCATTAAGTATCCCGCCTGGGAAGTACGGCCGCAAGGTTGAAACTCAAAGGAATT
   GACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGACGCAACGCGAAGAACCTTACCCAGGTTGGACATGCAC
   GTAGTAGAAAGGTGAAAGCCTGACGAGGTAGCAATACCAGCGTGNCTCAGGTGCTGCATGGCTGTCGTCAGCTCGTGCCG
   TGAGGTGTTGGGTTAAGTCCCGCAACGAGCGCAACCCCTGCTTTCAGTTGCTACCGGGTCATGCCGAGCACTCTGAAAGG
   ACTGCCCAGGATAACGGGGAGGAAGGTGGGGATGACGTCAAGTCAGCATGGCCTTTATGCCTGGGGCCACACACGTGCTA
   CAATGGCCGGTACAAAGCGCTGCAAACCTGCAAAGGGGAGCCAATCGCAAAAAACCGGCCTCAGTTCAGATTGAGGTCTG
   CAACTCGACCTCATGAAGGCGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTTCCCGGGCCTTGTACA
   CACCGCCCGTCACACCACGAAAGCCTGTTGTACCTGAAGTCGCCCAAGCCAACCGCAAGGAGGCAGGCGCCCACGGTATG
   GCCGGTGATTGGGGTGAA"
    )
  
  blast_db_path <-
    file.path(system.file(package = 'rCRUX', 'mock-db/blastdb'), 'mock-db')
  
  blastn_output <-
    run_blastn(
      fasta = aggregate_fasta,
      db = blast_db_path,
      evalue = 1e-6,
      align = 50000,
      coverage = 50,
      perID = 90,
      num_threads = 1
    )
  
  nitro_ids <- unique(blastn_output$accession)
  
  expect_true(all(
    nitro_ids %in%  c(
      "FP929003.1",
      "EU559167.1",
      "DQ059545.1",
      "CP011801.1",
      "AF155152.1",
      "HM485589.1",
      "AB818959.1",
      "HQ686084.1"
    )
  ))
  
})
